# Generated by Django 3.2.6 on 2021-08-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('dni', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('date_of_birth', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(choices=[('A', 'Anorexia'), ('B', 'Bulimia'), ('O', 'Obesidad')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_food', models.CharField(choices=[('D', 'Desayuno'), ('A', 'Almuerzo'), ('M', 'Merienda'), ('C', 'Cena')], default='D', max_length=1)),
                ('primary_food', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_food', models.CharField(blank=True, max_length=150, null=True)),
                ('drink', models.CharField(blank=True, max_length=100, null=True)),
                ('afters', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1)),
                ('afters_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tentation', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1)),
                ('tentation_name', models.CharField(blank=True, max_length=150, null=True)),
                ('was_hungry', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
