# Generated by Django 3.2.6 on 2021-08-24 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfood',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
