# Generated by Django 3.2.6 on 2021-08-24 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_dailyfood_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfood',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
