# Generated by Django 3.2.6 on 2021-08-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_dailyfood_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='surname',
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
